version: "3"
services:
  db:
    image: postgres:11
    volumes:
      - datavol:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bulltein-board
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  datavol:
